[pytest]

# Folder containing all test cases
testpaths = tests

# Test file naming convention
python_files = test_*.py

# Test class naming convention
python_classes = Test*

# Test method naming convention
python_functions = test_*

# Default command-line options
addopts =
    -v
    -s
    --tb=short
    --html=reports/html/report.html
    --self-contained-html

# Custom markers
markers =
    smoke: Smoke Test Suite
    regression: Regression Test Suite
    sanity: Sanity Test Suite
    login: Login related tests
    logout: Logout related tests
    dashboard: Dashboard related tests
    navigation: Navigation related tests
    manage: manage page related tests
    monitor: monitor related tests
    designer: designer related tests
    vault: setup related tests
    supplemental_logging: Supplemental Logging tests
    parameter_file: Setup Parameter File tab tests
    config_tables: Setup Config Tables tab tests
    connections: Setup Connections tab tests
    purge_cdc_files: Setup Purge CDC Files tab tests
    assessment: Pre-Migration Assessment tests
    initial_load: Homogeneous/Heterogeneous Initial Load tests
    dataflow: Dataflow screen tests
    conflict_resolution: Conflict Resolution screen tests
    analyze_objects: Analyze Objects screen tests
    analyze_trails: Analyze Trails screen tests
    troubleshoot: Troubleshoot screen tests
    logfile: LogFile screen tests
    compare_pad: Compare Pad screen tests
    ui: User Interface tests
    negative

log_cli = true
log_cli_level = INFO
