[pytest]

# Folder containing all test cases
testpaths = tests

# Test file naming convention
python_files = test_*.py

# Test class naming convention
python_classes = Test*

# Test method naming convention
python_functions = test_*

# Default command-line options
addopts =
    -v
    -s
    --tb=short

# Custom markers
markers =
    smoke: Smoke Test Suite
    regression: Regression Test Suite
    sanity: Sanity Test Suite